version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      repo-tools:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /basic-pubky-app
    schedule:
      interval: weekly
    groups:
      pubky-stack:
        patterns:
          - '@synonymdev/pubky'
          - '@synonymdev/pubky-*'
          - '@synonymdev/*pubky*'
  - package-ecosystem: npm
    directory: /vite-starter
    schedule:
      interval: weekly
    groups:
      vite-starter:
        patterns:
          - '*'
