version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      pubky-stack:
        patterns:
          - '@synonymdev/pubky'
          - '@synonymdev/pubky-*'
          - '@synonymdev/*pubky*'
